### ISSUE TITLE
Debian Bullseye will not run install.sh

### ISSUE THREAD

**Issue by xdsquared** [openDsh/dash#105]
Debian Bullseye won't run install.sh. Says that package qt5-default has no installation candidate. Here's a clip of the terminal 

![image](https://user-images.githubusercontent.com/35746868/143691163-05b6c689-2146-4773-a7b3-03b89b11d763.png)

**Comment by robert5974** [comment]
I seemed to have fixed the dependencies in the install.sh script for Bullseye.  Had to add the following to replace _qt5-default_ (which was removed because all Debian based distros have qt5 as default now and apparently caused more issues than it solved according to Qt):
qtbase5-dev 
qtchooser 
qt5-qmake 
qtbase5-dev-tools

Qt-gstreamer will also fail to compile with Bullseye.  There is a package you can install though.  I do believe that is the package name "qt-gstreamer" and that will take car of it.  

Edit the install.sh script to skip the building of it or use the install.sh script to build each leg of the whole project like this "./install.sh --openauto" or "./install.sh --dash".

The four parts the script builds is aasdk, qt-gstreamer, openauto, and dash.  If you individually build these, don't forget to create the udev rules for usb.  It will be the last part of that script if you need it.

The default firmware version of Bullseye also will cause you a problem when connecting your phone.  Connecting phone to Openauto will show a white screen.  This has not been resolved as of yet.  I have a workaround but it hasn't been extensively tested and will cause high CPU usage.

**Comment by robert5974** [comment]
Oh when I said I "fixed" the install.sh script, I didn't mean in the repo.  I only got it working locally.  All changes you will have to make yourself locally on your pi.

**Comment by icecube45** [comment]
The short of it is that dash isn't compatible with bullseye yet - among other issues, bullseye has removed openmax support, so it will be especially broken on Pi 3s

**Comment by jakka351** [comment]
has anyone tried on x86 debian buster?

**Comment by egisz** [comment]
> Qt-gstreamer will also fail to compile with Bullseye. There is a package you can install though. I do believe that is the package name "qt-gstreamer" and that will take car of it.

actual package name is **libqt5gstreamer-dev**

**Comment by robert5974** [comment]
I don't know that anyone has tried on an actual Debian install on x86 hw but I would think you could get it working manually easily depending on versions of packages.

Qt-Gstreamer can be built just as we always do but if using gstreamer 1.16 or 1.18, you have to patch the source of qt-gstreamer before it will compile.  I've shared that on Slack in the development channel.  Along with that you have to adjust some packages to install on Bullseye.  Some of us have worked through some of those adjustments and have gotten it all built.  I haven't been able to use it with the white screen issue happening on the OpenAuto tab.

**Comment by icecube45** [comment]
Yes, we should be building qt-gstreamer from source, as the version in the raspbian repos is out of date and has a few bugs that would affect dash (like the red tint issue). I'll try and get the patch incorporated into the install script some time this week.

**Comment by Tysonpower** [comment]
I really hope this get's fixed,,,i'm also stuck on my PI400 on Bullseye. no chance getting around the white screen bug so far.

**Comment by robert5974** [comment]
There is a way around it but it isn't recommended as it would spike the CPU
usage.  I've found a way to use it but it isn't zero copy streaming.  It
relies on passing to the CPU instead of going straight through to the GPU
for decoding.  We are working on it.  Icecube45 actually just put a PR in
that I'm testing that provides the debugging function of generating the
gstreamer pipeline. Hopefully it can point us in a direction toward fixing
it.

Robert Crowley

**Comment by icecube45** [comment]
> I really hope this get's fixed,,,i'm also stuck on my PI400 on Bullseye. no chance getting around the white screen bug so far.

I have a workaround for the white screen issue in [my branch of openauto](https://github.com/icecube45/openauto/tree/terrible_h264_hack) - it adds a new setting in openauto.ini that needs to be set to true, but should work after that. Note that it [requires h264bitstream to be installed](https://github.com/aizvorski/h264bitstream/issues)
![image](https://user-images.githubusercontent.com/1614007/151716188-72fc7158-7953-4919-970e-00318a48f11c.png)

Just informing those affected until this is (hopefully) fixed upstream

**Comment by icecube45** [comment]
Should be fixed by #112  and #107

**Comment by MadLad1Clip** [comment]
Seem to get this problem on my Pi3

**Comment by robert5974** [comment]
Where does it fail. For you?

Robert Crowley

**Comment by MadLad1Clip** [comment]
Seems to keep getting to this point and failing
![image](https://user-images.githubusercontent.com/5630104/233845119-c44ef474-fd42-49f3-b340-73c6b0ca1cb1.png)

**Comment by MadLad1Clip** [comment]
Tried what I can to fix it but think i am well out my level of knowledge, if anyone knows a fix let me know but for now i cant find anything posted to fix this so ill try another app till i know a fix is out there.

**Comment by MadLad1Clip** [comment]
Ok was my error due to intalling from SSH

**Comment by robert5974** [comment]
Yes.  It finished but couldn't launch the gui

Robert Crowley
