### ISSUE TITLE
RasberryPi freezes during install

### ISSUE THREAD

**Issue by Expresion** [openDsh/dash#162]
[ 83%] Building CXX object CMakeFiles/aasdk.dir/src/Channel/AV/AudioServiceChannel.cpp.o

RaspberryPi 3b+

**Comment by BogoniZeno** [comment]
i just installed it on my rpi 3b and had the same problems, check #161 last comment and try that

**Comment by rsjudka** [comment]
how much RAM does your pi have and how much have you allocated for the GPU?
are you installing from a GUI or terminal?

its possible the pi runs out of memory when you build aasdk/openauto, haven't profiled how much the compilation actually takes but if you run a very slim system (at least while building) it should complete

**Comment by breakingspell** [comment]
Hey y'all, I tried a quick change to set one less parallel job (-j1) on the AASDK and gstreamer build steps, but it hangs on Openauto make later, even on -j1 flag. The base system image at idle takes ~96M, and the OOM occurs after 800M used of 907M (with all 200M swap used). 

Turns out increasing system swap to 1GB allows the entire build to run at -j4 on RPi3 (2024-03 raspios-lite), albeit much slower than on a Pi 4 or within a virtual machine like #161.
