### ISSUE TITLE
Debian x86/x64 White Screen on AA Connect.

### ISSUE THREAD

**Issue by jakka351** [openDsh/dash#180]
# Issue

Running latest version of Dash on a fresh install of Debian Linux with Gnome Desktop, AMD64 version of Linux. Android Auto appears to connect and be running phone side, however in Dash displays a blank white screen. Is there a fix for this yet?
*Make sure you are running the latest version before reporting an issue.*

## Hardware

| Device             | Connection Method | Screen                       | Mobile Device     | Android Auto Version |
| ------------------ | ----------------- | ---------------------------- | ----------------- | -------------------- |
| Panasonic Toughbook Debian x64 | USB Cable  | Motorola Moto G |        |

Installation Method: Install.sh

## Description of problem:

White screen on aa connect 

## Expected Result:

Standard AA display 

## Problem-relevant steps to reproduce:

1. Plug in phone
1. 
1. 

## Traceback (if applicable):
```bash

```

## Additional info:

Additional Info

**Comment by robert5974** [comment]
Yes, there was very recently a fix submitted for the white screen and it
seems to have stemmed from RtAudio which is why toggling RtAudio to QtAudio
would "fix" the issue but change the audio.  I thought the PR was recently
merged but I'd have to verify.  Go check the latest commits and I think the
fix should be in the last 3 or 4 PRs.
If I'm right, the fix is in the OpenAuto code so you pull the update and
recompile just OpenAuto by command ".\install.sh --openauto".  I didn't
have the white screen issue at the time to verify an actual fix but it
compiled fine for me.

Robert Crowley

**Comment by jakka351** [comment]
As someone else has said in a different issue, disabling RT Audio fixed this issue. Closing

**Comment by jakka351** [comment]
Closed
